# fly.toml app configuration file generated for medquest on 2025-08-02T11:35:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medquest'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'medquest_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = '15s'
  timeout = '10s'
  grace_period = '60s'
  method = 'GET'
  path = '/api/config'
  protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
